Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,7 +7,7 @@ on:
 
 
 evn:
-  HEALTHCHECK_URL: http://34.228.255.233:5000
+  HEALTHCHECK_URL: http://13.200.242.191:5000
 
 jobs:
   Build-test-deploy:
@@ -53,4 +53,4 @@ health:
           curl -s -o /dev/null -w "%{http_code}" $HEALTHCHECK_URL | grep "200" && echo "Health check passed" && exit 0 || echo "Waiting for service..";
           sleep 5;
         done;
-        echo "Health check failed" && exit 1
+        echo "Health check failed****" && exit 1
